### ISSUE TITLE
Considerar termos do padrão Dublin Core

### ISSUE THREAD

**Issue by diogok** [edalcin/recursos_inf_biodiversidade#4]
Como o foco são os metadados dos recursos, talvez seja bom considerar utilizar os mesmos termos do DublinCore para os campos compativeis, como:

- type ou subject
- title (name)
- creator (author)
- description
- spatial (spatialCoverage)
- temporal (temporalCoverage)

**Comment by edalcin** [comment]
Sim! Estou achando que o http://schema.org/docs/full.html atende bem, e está também no contexto. Parece que ele "bebeu" do DC em vários casos.

**Comment by edalcin** [comment]
No mapeamento atualizei os termos com link para o schema.org

**Comment by diogok** [comment]
Ficou bom o mapeamento das diferentes fontes!
